blank_issues_enabled: false
issue_templates:
  - name: ğŸ Bug Report
    description: ë²„ê·¸ ì œë³´
    title: "[FIX] "
    labels: bug
    assignees: ''
    template: bug_template.yml
  - name: âœ¨ Feature Request
    description: ìƒˆë¡œìš´ ê¸°ëŠ¥ ì œì•ˆ
    title: "[FEAT] "
    labels: feat
    assignees: ''
    template: feature_template.yml
  - name: âœ‰ï¸ Other Issues
    description: ê·¸ ì™¸ ëª¨ë“  ì‘ì—…
    title: "[ENHANCE] "
    labels: enhancement
    assignees: ""
    template: request_template.yml